### ISSUE TITLE
Can't connect to MySQL server

### ISSUE THREAD

**Issue by Don-Swanson** [open-eats/OpenEats#94]
Hello, have an issue on a new install...
After making prescribed config changes, I run the `./quick-start.py`, and everything appears to startup. I have it connecting to a remote DB.

However after startup, when I try to run `docker-compose -f docker-prod.yml run --rm --entrypoint 'python manage.py createsuperuser' api` I get the following error...

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2003, 'Can\'t connect to MySQL server on \'172.28.0.100\' (110 "Operation timed out")')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 59, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 352, in execute
    self.check_migrations()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 442, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2003, 'Can\'t connect to MySQL server on \'172.28.0.100\' (110 "Operation timed out")')
```

The issue that I have is that it obviously could connect to the database during the install/startup, because what once was an empty database has tables in it when I look. Any ideas?

**Comment by Don-Swanson** [comment]
I figured out the issue... the `docker-compose -f docker-prod.yml run --rm --entrypoint 'python manage.py createsuperuser' api` command doesn't respect the `docker-prod.override.yml` file and thus started in a different docker network.

**Comment by RyanNoelk** [comment]
Glad you figured it out. I'll be sure to update the docs.

**Comment by lathrum** [comment]
So how do you fix it?  I'm having the same issue.

**Comment by Don-Swanson** [comment]
I use Portainer for a GUI to easily mange my docker containers, so I consoled into the API container that was created by the script via portainer and manually ran the command `python manage.py createsuperuser` .

I guess a real resolution to this would be for the devs to find a way to have the `docker-compose -f docker-prod.yml run --rm --entrypoint 'python manage.py createsuperuser' api` command respect the contents of the override file.

**Comment by RyanNoelk** [comment]
You can chain the yml files together like: 
```
docker-compose -f docker-prod.yml -f docker-prod.version.yml -f docker-prod.override.yml run --rm --entrypoint 'python manage.py createsuperuser' api
```

This is what is happening in the quick start script but, I must have missed it in the docs.

See: https://github.com/open-eats/OpenEats/blob/master/quick-start.py#L113-L116 for an example.

**Comment by lathrum** [comment]
Running the above "chained" command still gives the MariaDB access error, though.

**Comment by RyanNoelk** [comment]
Are you running ur DB locally or via docker containers?

**Comment by lathrum** [comment]
Default setup, so in the docker container.

**Comment by RyanNoelk** [comment]
> Default setup, so in the docker container.

seems more like: https://github.com/open-eats/OpenEats/issues/93

I'm not sure what the issue is yet, I'm looking into it.

**Comment by lathrum** [comment]
Any luck?  The wife has a bunch of recipes laid out waiting to input into somewhere and your app looks promising :)

**Comment by lathrum** [comment]
This issue isn't resolved...

**Comment by Don-Swanson** [comment]
Did you try my suggestion of using portainer and just using the console to run the command?

**Comment by lathrum** [comment]
It's a workaround but doesn't resolve the root cause (which should be fixed if anyone else tries to use it).  I wasn't planning on learning Portainer since I'm not very experienced at this, but I suppose I should at this point since the dev is probably busy with his day job.

**Comment by lathrum** [comment]
In looking at #93 it appears that's the same issue, so this is probably fine to close, anyways.  Cheers :)

**Comment by Don-Swanson** [comment]
That was my main reasoning for it.
